// Generated by Wrangler by running `wrangler types`
// After creating resources, run: npx wrangler types

interface Env {
	AI: Ai;
	VECTOR_INDEX: Vectorize;
	DB: D1Database;
	RAG_BUCKET: R2Bucket;
	RAG_WORKFLOW: Workflow;
}
